In [10]:
import cv2

In [11]:
import numpy as np

In [3]:
path = "opencvimg.png"

In [4]:
img = cv2.imread(path)
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [5]:
img[0,0]

array([255, 255, 255], dtype=uint8)

In [6]:
img[40,50]

array([255, 255, 255], dtype=uint8)

In [7]:
(b,g,r) = img[50,30]

In [8]:
print("(0,0) - Red: {},Green:{} ,Blue:{}".format(r,g,b))

(0,0) - Red: 255,Green:255 ,Blue:255


In [9]:
blue = img[100,100,0]

In [10]:
blue

255

In [11]:
green = img[100,100,1]

In [12]:
green

255

In [14]:
img.item(100,100,2)

255

In [15]:
img.itemset((100,100,2),100)

In [16]:
img.item(100,100,2)

100

In [3]:
import matplotlib.pyplot as plt

In [12]:
img = cv2.imread("yesiltepe.jpg")
corner = img[0:100,0:100] #[y.axis,x.axis]

In [13]:
img

array([[[251, 242, 233],
        [252, 243, 234],
        [252, 243, 234],
        ...,
        [242, 229, 221],
        [242, 230, 220],
        [242, 230, 220]],

       [[251, 242, 233],
        [252, 243, 234],
        [252, 243, 234],
        ...,
        [243, 230, 222],
        [242, 230, 220],
        [242, 230, 220]],

       [[251, 242, 233],
        [251, 242, 233],
        [252, 243, 234],
        ...,
        [243, 230, 222],
        [243, 230, 222],
        [243, 230, 222]],

       ...,

       [[ 28,  23,  24],
        [ 29,  24,  25],
        [ 29,  24,  25],
        ...,
        [ 45,  59,  65],
        [ 50,  64,  70],
        [ 57,  71,  77]],

       [[ 28,  23,  24],
        [ 30,  25,  26],
        [ 30,  25,  26],
        ...,
        [ 27,  41,  47],
        [ 34,  48,  54],
        [ 45,  59,  65]],

       [[ 29,  24,  25],
        [ 29,  24,  25],
        [ 29,  24,  25],
        ...,
        [ 14,  26,  32],
        [ 17,  29,  35],
        [ 24,  36,  42]]

In [9]:
cv2.imshow("test",img)
cv2.imshow("corner",corner)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
img = cv2.imread("opencvimg.png")

print(img.shape) #height , width , channel
#channel=3 -->color
#channel=1 -->grayscale

(608, 1400, 3)


In [17]:
cv2.imshow("resim",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
img = cv2.imread("yesiltepe.jpg")
print(img.shape)

roi = img[0:500,0:500]

(1369, 2048, 3)


In [25]:
cv2.imshow("yesiltepe",img)
cv2.imshow("roi",roi)
cv2.waitKey(0)
cv2.destroyAllWindows()